# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/govind/code/RF

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/govind/code/RF

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/govind/code/RF/CMakeFiles /home/govind/code/RF/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/govind/code/RF/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named clf

# Build rule for target.
clf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clf
.PHONY : clf

# fast build rule for target.
clf/fast:
	$(MAKE) -f CMakeFiles/clf.dir/build.make CMakeFiles/clf.dir/build
.PHONY : clf/fast

Classifier/classifierforest.o: Classifier/classifierforest.cpp.o

.PHONY : Classifier/classifierforest.o

# target to build an object file
Classifier/classifierforest.cpp.o:
	$(MAKE) -f CMakeFiles/clf.dir/build.make CMakeFiles/clf.dir/Classifier/classifierforest.cpp.o
.PHONY : Classifier/classifierforest.cpp.o

Classifier/classifierforest.i: Classifier/classifierforest.cpp.i

.PHONY : Classifier/classifierforest.i

# target to preprocess a source file
Classifier/classifierforest.cpp.i:
	$(MAKE) -f CMakeFiles/clf.dir/build.make CMakeFiles/clf.dir/Classifier/classifierforest.cpp.i
.PHONY : Classifier/classifierforest.cpp.i

Classifier/classifierforest.s: Classifier/classifierforest.cpp.s

.PHONY : Classifier/classifierforest.s

# target to generate assembly for a file
Classifier/classifierforest.cpp.s:
	$(MAKE) -f CMakeFiles/clf.dir/build.make CMakeFiles/clf.dir/Classifier/classifierforest.cpp.s
.PHONY : Classifier/classifierforest.cpp.s

Classifier/classifiertree.o: Classifier/classifiertree.cpp.o

.PHONY : Classifier/classifiertree.o

# target to build an object file
Classifier/classifiertree.cpp.o:
	$(MAKE) -f CMakeFiles/clf.dir/build.make CMakeFiles/clf.dir/Classifier/classifiertree.cpp.o
.PHONY : Classifier/classifiertree.cpp.o

Classifier/classifiertree.i: Classifier/classifiertree.cpp.i

.PHONY : Classifier/classifiertree.i

# target to preprocess a source file
Classifier/classifiertree.cpp.i:
	$(MAKE) -f CMakeFiles/clf.dir/build.make CMakeFiles/clf.dir/Classifier/classifiertree.cpp.i
.PHONY : Classifier/classifiertree.cpp.i

Classifier/classifiertree.s: Classifier/classifiertree.cpp.s

.PHONY : Classifier/classifiertree.s

# target to generate assembly for a file
Classifier/classifiertree.cpp.s:
	$(MAKE) -f CMakeFiles/clf.dir/build.make CMakeFiles/clf.dir/Classifier/classifiertree.cpp.s
.PHONY : Classifier/classifiertree.cpp.s

Classifier/main.o: Classifier/main.cpp.o

.PHONY : Classifier/main.o

# target to build an object file
Classifier/main.cpp.o:
	$(MAKE) -f CMakeFiles/clf.dir/build.make CMakeFiles/clf.dir/Classifier/main.cpp.o
.PHONY : Classifier/main.cpp.o

Classifier/main.i: Classifier/main.cpp.i

.PHONY : Classifier/main.i

# target to preprocess a source file
Classifier/main.cpp.i:
	$(MAKE) -f CMakeFiles/clf.dir/build.make CMakeFiles/clf.dir/Classifier/main.cpp.i
.PHONY : Classifier/main.cpp.i

Classifier/main.s: Classifier/main.cpp.s

.PHONY : Classifier/main.s

# target to generate assembly for a file
Classifier/main.cpp.s:
	$(MAKE) -f CMakeFiles/clf.dir/build.make CMakeFiles/clf.dir/Classifier/main.cpp.s
.PHONY : Classifier/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... clf"
	@echo "... Classifier/classifierforest.o"
	@echo "... Classifier/classifierforest.i"
	@echo "... Classifier/classifierforest.s"
	@echo "... Classifier/classifiertree.o"
	@echo "... Classifier/classifiertree.i"
	@echo "... Classifier/classifiertree.s"
	@echo "... Classifier/main.o"
	@echo "... Classifier/main.i"
	@echo "... Classifier/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

